# Generated by Django 4.1 on 2022-08-14 05:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_story_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
